import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Navigation/ResponsiveNav";
import Footer from "@/components/Footer/Footer";

const poppins = JetBrains_Mono({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Urisat | wise in blockchain development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
       <ResponsiveNav/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
